#pragma once

#ifndef PLAYER_LINUX_VERSION
#define PLAYER_LINUX_VERSION "0.1.0"
#endif
#ifndef PLAYER_LINUX_PARITY_AD
#define PLAYER_LINUX_PARITY_AD "2.15/115"
#endif

#define PLAYER_LINUX_VERSION_STR PLAYER_LINUX_VERSION
#define PLAYER_LINUX_PARITY_STR PLAYER_LINUX_PARITY_AD
#define PLAYER_LINUX_PLATFORM "linux"
