import type { SystemSetting } from '../services/settingsService';

type DefaultFinancialSetting = Omit<
  SystemSetting,
  'id' | 'createdAt' | 'updatedAt' | 'value' | 'options'
> & {
  value: string | boolean | number;
  options?: string[] | null;
  validation?: string | null;
};

/** Garantidos em runtime se ausentes na base (install antigo sem seeds financeiros). */
export const DEFAULT_FINANCIAL_SETTINGS: DefaultFinancialSetting[] = [
  {
    key: 'financial.worker_enabled',
    value: 'true',
    type: 'boolean',
    category: 'financial',
    description:
      'Worker financeiro (crons de faturas, lembretes e bloqueio). Desligue para pausar rotinas sem reiniciar o servidor.',
    isPublic: false,
    isEditable: true,
    defaultValue: 'true',
    validation: '^(true|false)$',
    options: ['true', 'false'],
  },
  {
    key: 'financial.merchant_whatsapp_number',
    value: '',
    type: 'string',
    category: 'financial',
    description: 'WhatsApp do financeiro da plataforma (link wa.me nos e-mails). Apenas dígitos, com DDI.',
    isPublic: false,
    isEditable: true,
    defaultValue: '',
  },
  {
    key: 'financial.smtp_enabled',
    value: 'false',
    type: 'boolean',
    category: 'financial',
    description: 'Habilita envio de e-mails (lembretes, bloqueio por inadimplência, etc.)',
    isPublic: false,
    isEditable: true,
    defaultValue: 'false',
    validation: '^(true|false)$',
    options: ['true', 'false'],
  },
  {
    key: 'financial.smtp_host',
    value: 'smtp.gmail.com',
    type: 'string',
    category: 'financial',
    description: 'Servidor SMTP (host)',
    isPublic: false,
    isEditable: true,
    defaultValue: 'smtp.gmail.com',
  },
  {
    key: 'financial.smtp_port',
    value: '587',
    type: 'number',
    category: 'financial',
    description: 'Porta SMTP',
    isPublic: false,
    isEditable: true,
    defaultValue: '587',
    validation: '^[0-9]+$',
  },
  {
    key: 'financial.smtp_secure',
    value: 'false',
    type: 'boolean',
    category: 'financial',
    description: 'SMTP SSL direto (porta 465). Para STARTTLS na 587, deixe false.',
    isPublic: false,
    isEditable: true,
    defaultValue: 'false',
    validation: '^(true|false)$',
    options: ['true', 'false'],
  },
  {
    key: 'financial.smtp_user',
    value: '',
    type: 'string',
    category: 'financial',
    description: 'Usuário SMTP',
    isPublic: false,
    isEditable: true,
    defaultValue: '',
  },
  {
    key: 'financial.smtp_pass',
    value: '',
    type: 'string',
    category: 'financial',
    description: 'Senha SMTP (mascarada na UI; deixe em branco ao salvar para manter a atual)',
    isPublic: false,
    isEditable: true,
    defaultValue: '',
  },
  {
    key: 'financial.smtp_from',
    value: 'Smart Signage <noreply@smartsignage.com>',
    type: 'string',
    category: 'financial',
    description: 'Remetente dos e-mails (From)',
    isPublic: false,
    isEditable: true,
    defaultValue: 'Smart Signage <noreply@smartsignage.com>',
  },
  {
    key: 'financial.smtp_tls_reject_unauthorized',
    value: 'true',
    type: 'boolean',
    category: 'financial',
    description: 'Rejeitar certificado SMTP inválido (TLS)',
    isPublic: false,
    isEditable: true,
    defaultValue: 'true',
    validation: '^(true|false)$',
    options: ['true', 'false'],
  },
  {
    key: 'financial.whatsapp_api_token',
    value: '',
    type: 'string',
    category: 'financial',
    description:
      'Token Meta Cloud API (WhatsApp Business). Deixe vazio para usar apenas link wa.me.',
    isPublic: false,
    isEditable: true,
    defaultValue: '',
  },
  {
    key: 'financial.whatsapp_phone_number_id',
    value: '',
    type: 'string',
    category: 'financial',
    description: 'Phone Number ID da Meta Cloud API (WhatsApp)',
    isPublic: false,
    isEditable: true,
    defaultValue: '',
  },
  {
    key: 'financial.whatsapp_api_version',
    value: 'v21.0',
    type: 'string',
    category: 'financial',
    description: 'Versão da Graph API Meta (WhatsApp)',
    isPublic: false,
    isEditable: true,
    defaultValue: 'v21.0',
  },
  {
    key: 'financial.block_publish_on_overdue',
    value: 'true',
    type: 'boolean',
    category: 'financial',
    description:
      'Bloqueia novas publicações (Publicar em Tela, campanhas ativas) quando o anunciante tem prestações vencidas',
    isPublic: false,
    isEditable: true,
    defaultValue: 'true',
    validation: '^(true|false)$',
    options: ['true', 'false'],
  },
  {
    key: 'financial.admin_override_overdue_block',
    value: 'true',
    type: 'boolean',
    category: 'financial',
    description:
      'Permite owner_system, admin_sql e admin publicar mesmo com prestações vencidas (override operacional)',
    isPublic: false,
    isEditable: true,
    defaultValue: 'true',
    validation: '^(true|false)$',
    options: ['true', 'false'],
  },
  {
    key: 'financial.block_publish_overdue_grace_days',
    value: '0',
    type: 'number',
    category: 'financial',
    description:
      'Dias de tolerância após o vencimento antes de bloquear publicações e pausar campanhas (0 = bloqueia no 1º dia após vencimento)',
    isPublic: false,
    isEditable: true,
    defaultValue: '0',
    validation: '^[0-9]+$',
  },
  {
    key: 'financial.auto_pause_campaigns_on_block',
    value: 'true',
    type: 'boolean',
    category: 'financial',
    description:
      'Pausa automaticamente campanhas ativas quando o bloqueio por inadimplência entra em vigor',
    isPublic: false,
    isEditable: true,
    defaultValue: 'true',
    validation: '^(true|false)$',
    options: ['true', 'false'],
  },
  {
    key: 'financial.notify_block_email_enabled',
    value: 'true',
    type: 'boolean',
    category: 'financial',
    description: 'Envia e-mail padronizado ao anunciante quando o bloqueio automático é aplicado',
    isPublic: false,
    isEditable: true,
    defaultValue: 'true',
    validation: '^(true|false)$',
    options: ['true', 'false'],
  },
  {
    key: 'financial.notify_block_whatsapp_enabled',
    value: 'true',
    type: 'boolean',
    category: 'financial',
    description:
      'Envia WhatsApp ao anunciante (Meta Cloud API se configurada; senão link wa.me no e-mail)',
    isPublic: false,
    isEditable: true,
    defaultValue: 'true',
    validation: '^(true|false)$',
    options: ['true', 'false'],
  },
  {
    key: 'financial.overdue_block_email_subject',
    value: 'Publicação suspensa — {{subscriber_name}} ({{overdue_count}} prestação(ões) em atraso)',
    type: 'string',
    category: 'financial',
    description:
      'Assunto do e-mail de bloqueio. Placeholders: {{subscriber_name}}, {{overdue_count}}, {{amount_total}}, {{grace_days}}, {{days_overdue}}, {{billing_url}}, {{invoice_list}}, {{merchant_name}}',
    isPublic: false,
    isEditable: true,
    defaultValue:
      'Publicação suspensa — {{subscriber_name}} ({{overdue_count}} prestação(ões) em atraso)',
  },
  {
    key: 'financial.overdue_block_email_body',
    value:
      'Olá {{subscriber_name}},\n\nA publicação nas telas foi suspensa após {{grace_days}} dia(s) de tolerância.\n\nPrestações em atraso: {{overdue_count}}\nValor total: {{amount_total}}\nMaior atraso: {{days_overdue}} dia(s)\n\n{{invoice_list}}\n\nRegularize: {{billing_url}}\n\n{{merchant_name}}',
    type: 'string',
    category: 'financial',
    description: 'Corpo do e-mail de bloqueio (texto). Use os mesmos placeholders do assunto.',
    isPublic: false,
    isEditable: true,
    defaultValue:
      'Olá {{subscriber_name}},\n\nA publicação nas telas foi suspensa após {{grace_days}} dia(s) de tolerância.\n\nRegularize: {{billing_url}}',
  },
  {
    key: 'financial.overdue_block_whatsapp_message',
    value:
      'Olá {{subscriber_name}}, sua publicação foi suspensa por inadimplência ({{overdue_count}} prestação(ões), {{amount_total}}, {{days_overdue}} dia(s) de atraso). Regularize: {{billing_url}}',
    type: 'string',
    category: 'financial',
    description: 'Mensagem WhatsApp de bloqueio. Placeholders iguais ao e-mail.',
    isPublic: false,
    isEditable: true,
    defaultValue: 'Olá {{subscriber_name}}, regularize em {{billing_url}}',
  },
];
